apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
data:
  server.ovpn: |-
    port {{ .Values.service.port }}
    proto {{ lower .Values.service.protocol }}
    dev tun
    ca /secret/ca.crt
    cert /secret/tls.crt
    key /secret/tls.key
    dh /state/dh2048.pem
    topology subnet
    server {{ .Values.openvpn.networkAddr }} {{ .Values.openvpn.subnetMask }}
    push "redirect-gateway def1"
    push "dhcp-option DNS 8.8.8.8"
    push "dhcp-option DNS 8.8.4.4"
    {{- range .Values.openvpn.pushOptions }}
    push {{ . | quote }}
    {{- end }}
    keepalive 10 120
    tls-auth /state/ta.key 0
    tls-version-min 1.2
    tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
    auth SHA512
    cipher AES-256-CBC
    comp-lzo
    persist-key
    persist-tun
    verb 6
    user openvpn
    group openvpn

